name: Base CI
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test-build:
    permissions:
      contents: read
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun ci
#      - run: bun lint || true
      - run: bun test  --timeout 20000
      - name: Full Audit
        run: |
          echo "## Audit results (all severities)" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          bun audit 2>&1 | tee audit.log || true
          {
            echo '```'
            cat audit.log
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"

      - run: bun audit --audit-level=high
      - run: bun run build